### ISSUE TITLE
unable to CAP Operator Application Version Workload Service Account

### ISSUE THREAD

**Issue by sTb1337** [SAP/cap-operator#46]
Hello Team,

how do i set a different service account on CAP application versions -> workloads -> deploymentDefinition ? (https://sap.github.io/cap-operator/docs/reference/#sme.sap.com/v1alpha1.CommonDetails)

We want to manage a k8s application via CAP operator which needs to interact with k8s api inside the cluster.

Cheers,
Steffen

**Comment by Pavan-SAP** [comment]
Hi Steffen,

Thanks for reporting the issue.. we so far did not see the need to interact with K8s API server from within a "CAP application workload" and the other common use cases (for service account) could be covered via the supported network policy configs, hence we did not support Service Accounts yet.

However, we will soon add support for specifying a `ServiceAccounName` on CAP Application workloads with #49 

Thanks & Regards,
Pavan
