### ISSUE TITLE
Support for single-tenant CAP applications

### ISSUE THREAD

**Issue by NickyMateev** [SAP/cap-operator#52]
# Support for single-tenant CAP applications

Hello - looking at the CAP Operator documentation: https://sap.github.io/cap-operator/docs/usage/resources/

I'm left with the impression that the CAP Operator is intended for Multi-tenant CAP applications only.

**Is there a way to also use the CAP Operator for Single-tenant CAP applications?**

**Comment by Pavan-SAP** [comment]
Hi Nikolay,

The CAP Operator is built for multitenant apps and hence works by default assuming `cds/mtxs` (CAP multitenancy lib) component is always enabled.
 
If you still wish to use it to manage single tenant applications, you need to either:
- Enable and use cds mtxs component and rely on the default Tenant Operation that also creates the provider tenant. (the default command we inject uses `cds/mtxs` cli command to provision tenants)
OR
- Provide an own Command for TenantOperation that does the corresponding tenant handling (e.g. db schema, table creation) accordingly for the single (provider) tenant.
(For SAP HANA Clound for instance one can use an own hdi deployer imageand provide a custom command for TenantOperation to do the necessary tenant artefact deployment)

We do not really have any examples for that as we focus on multitenancy apps. But I hope that helps provide you with options to test/use it in single tenant mode.

Regards,
Pavan
