### ISSUE TITLE
Feature request: Configurable DestinationRule and Virtual Service

### ISSUE THREAD

**Issue by SujitThonse** [SAP/cap-operator#75]
---
Feature: Configurable DestinationRule and Virtual Service
---

**Problem**
According to the CAP Operator documentation, we should be able to use more replicas of the “CAP Appllication” for scaling purposes. In our application, we tested it by using 3 replicas.  But the expected “Round Robin” is not working. 98% of the requests are forwarded to the same replica while 2 other replicas are idle. This could be the case if there is a kind of statefulness like “session stickiness”. We should ensure that we do Round Robin to distribute the load.

**Suggession**
* As per Istio documentation, to have application load balancer we need Virtual service and Destination rule to be configurable: https://istio.io/latest/docs/concepts/traffic-management/#load-balancing-3-subsets

**Comment by Pavan-SAP** [comment]
Hi Sujit,

As most requests are routed via app router if there is already a logon session a sticky cookie is used to ensure the same pod gets the consequent requests. This is done to ensure app router functions as expected. See: https://www.npmjs.com/package/@sap/approuter#scaling

Hence we do not plan to expose configuring/overwriting our Destination Rule / Virtual Service configuration as of now.

Thanks & Regards,
Pavan
